import { canonicalMediaId } from '@trackt/shared';
import type { media } from './schema/media.js';

type MediaSeed = typeof media.$inferInsert;

/**
 * Dev/test fixture catalog spanning every media kind, keyed by canonical IDs so the
 * rows match what the central catalog will publish for the same works (ADR-0001).
 * The webtoon row is user-created and keeps a fixed random UUID.
 */
export const SEED_MEDIA: MediaSeed[] = [
  // Movies (identity provider: tmdb)
  {
    id: canonicalMediaId('movie', 603),
    kind: 'movie',
    title: 'The Matrix',
    slug: 'the-matrix-1999',
    synonyms: ['Matrix'],
    genres: ['action', 'science fiction'],
    year: 1999,
    releaseDate: '1999-03-31',
    status: 'ended',
    externalIds: { tmdb: 603, imdb: 'tt0133093' },
    description: 'A hacker learns the true nature of his reality.',
  },
  {
    id: canonicalMediaId('movie', 157336),
    kind: 'movie',
    title: 'Interstellar',
    slug: 'interstellar-2014',
    synonyms: [],
    genres: ['adventure', 'drama', 'science fiction'],
    year: 2014,
    releaseDate: '2014-11-05',
    status: 'ended',
    externalIds: { tmdb: 157336, imdb: 'tt0816692' },
    description: 'Explorers travel through a wormhole in search of a new home for humanity.',
  },
  {
    id: canonicalMediaId('movie', 129),
    kind: 'movie',
    title: 'Spirited Away',
    slug: 'spirited-away-2001',
    synonyms: ['千と千尋の神隠し', 'Sen to Chihiro no Kamikakushi'],
    genres: ['animation', 'fantasy'],
    year: 2001,
    releaseDate: '2001-07-20',
    status: 'ended',
    externalIds: { tmdb: 129, imdb: 'tt0245429' },
    description: 'A girl wanders into a world of spirits and must free her parents.',
  },
  // Series (identity provider: tmdb)
  {
    id: canonicalMediaId('series', 1396),
    kind: 'series',
    title: 'Breaking Bad',
    slug: 'breaking-bad-2008',
    synonyms: [],
    genres: ['crime', 'drama'],
    year: 2008,
    releaseDate: '2008-01-20',
    status: 'ended',
    seasonCount: 5,
    episodeCount: 62,
    externalIds: { tmdb: 1396, imdb: 'tt0903747', tvdb: 81189 },
    description: 'A chemistry teacher turns to manufacturing methamphetamine.',
  },
  {
    id: canonicalMediaId('series', 1438),
    kind: 'series',
    title: 'The Wire',
    slug: 'the-wire-2002',
    synonyms: [],
    genres: ['crime', 'drama'],
    year: 2002,
    releaseDate: '2002-06-02',
    status: 'ended',
    seasonCount: 5,
    episodeCount: 60,
    externalIds: { tmdb: 1438, imdb: 'tt0306414' },
    description: 'Baltimore through the eyes of drug dealers and law enforcement.',
  },
  {
    id: canonicalMediaId('series', 95396),
    kind: 'series',
    title: 'Severance',
    slug: 'severance-2022',
    synonyms: [],
    genres: ['drama', 'mystery', 'science fiction'],
    year: 2022,
    releaseDate: '2022-02-17',
    status: 'airing',
    seasonCount: 2,
    episodeCount: 19,
    externalIds: { tmdb: 95396, imdb: 'tt11280740' },
    description: 'Employees have their work and personal memories surgically divided.',
  },
  // Anime (identity provider: anilist)
  {
    id: canonicalMediaId('anime', 1),
    kind: 'anime',
    title: 'Cowboy Bebop',
    slug: 'cowboy-bebop-1998',
    synonyms: ['カウボーイビバップ'],
    genres: ['action', 'science fiction'],
    year: 1998,
    releaseDate: '1998-04-03',
    status: 'ended',
    seasonCount: 1,
    episodeCount: 26,
    externalIds: { anilist: 1, mal: 1 },
    description: 'Bounty hunters drift through space aboard the Bebop.',
  },
  {
    id: canonicalMediaId('anime', 154587),
    kind: 'anime',
    title: 'Frieren: Beyond Journey’s End',
    slug: 'frieren-beyond-journeys-end-2023',
    synonyms: ['葬送のフリーレン', 'Sousou no Frieren'],
    genres: ['adventure', 'drama', 'fantasy'],
    year: 2023,
    releaseDate: '2023-09-29',
    status: 'ended',
    seasonCount: 1,
    episodeCount: 28,
    externalIds: { anilist: 154587, mal: 52991 },
    description: 'An elf mage outlives her companions and retraces their journey.',
  },
  {
    id: canonicalMediaId('anime', 5114),
    kind: 'anime',
    title: 'Fullmetal Alchemist: Brotherhood',
    slug: 'fullmetal-alchemist-brotherhood-2009',
    synonyms: ['鋼の錬金術師 FULLMETAL ALCHEMIST', 'Hagane no Renkinjutsushi'],
    genres: ['action', 'adventure', 'fantasy'],
    year: 2009,
    releaseDate: '2009-04-05',
    status: 'ended',
    seasonCount: 1,
    episodeCount: 64,
    externalIds: { anilist: 5114, mal: 5114 },
    description: 'Two brothers seek the Philosopher’s Stone to restore their bodies.',
  },
  // Manga (identity provider: anilist)
  {
    id: canonicalMediaId('manga', 30002),
    kind: 'manga',
    title: 'Berserk',
    slug: 'berserk-1989',
    synonyms: ['ベルセルク'],
    genres: ['action', 'dark fantasy'],
    year: 1989,
    releaseDate: '1989-08-25',
    status: 'publishing',
    volumeCount: 42,
    chapterCount: 380,
    externalIds: { anilist: 30002, mal: 2 },
    description: 'A lone mercenary battles fate in a medieval dark-fantasy world.',
  },
  {
    id: canonicalMediaId('manga', 30013),
    kind: 'manga',
    title: 'One Piece',
    slug: 'one-piece-1997',
    synonyms: ['ワンピース'],
    genres: ['action', 'adventure', 'comedy'],
    year: 1997,
    releaseDate: '1997-07-22',
    status: 'publishing',
    volumeCount: 110,
    chapterCount: 1120,
    externalIds: { anilist: 30013, mal: 13 },
    description: 'Monkey D. Luffy sails to find the One Piece and become Pirate King.',
  },
  {
    id: canonicalMediaId('manga', 105778),
    kind: 'manga',
    title: 'Chainsaw Man',
    slug: 'chainsaw-man-2018',
    synonyms: ['チェンソーマン'],
    genres: ['action', 'horror'],
    year: 2018,
    releaseDate: '2018-12-03',
    status: 'publishing',
    volumeCount: 20,
    chapterCount: 180,
    externalIds: { anilist: 105778, mal: 116778 },
    description: 'A devil hunter merges with his chainsaw devil to survive.',
  },
  // Webtoon — user-created: fixed random UUID (no identity provider for webtoons).
  {
    id: '7b0c6d3e-2f41-4a9d-9c1c-8f4d2a6b5e10',
    kind: 'webtoon',
    title: 'Cosmic Delivery Club',
    slug: 'cosmic-delivery-club',
    synonyms: [],
    genres: ['comedy', 'slice of life'],
    year: 2024,
    status: 'publishing',
    chapterCount: 47,
    externalIds: {},
    source: 'user',
    moderation: 'unverified',
    description: 'A fictional dev-seed webtoon about couriers who deliver across galaxies.',
  },
];
